name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test -- --coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage/

  deploy-production:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      # Primero sincronizamos las variables
      - name: Sync Environment Variables
        # Removemos las variables existentes
        run: |
          vercel env rm AUTH_SECRET production --token=${{ secrets.VERCEL_TOKEN }} -y || true
          vercel env rm AUTH0_ISSUER production --token=${{ secrets.VERCEL_TOKEN }} -y || true
          vercel env rm AUTH0_CLIENT_ID production --token=${{ secrets.VERCEL_TOKEN }} -y || true
          vercel env rm AUTH0_CLIENT_SECRET production --token=${{ secrets.VERCEL_TOKEN }} -y || true
          vercel env rm AUTH0_BASE_URL production --token=${{ secrets.VERCEL_TOKEN }} -y || true
          vercel env rm API_URL production --token=${{ secrets.VERCEL_TOKEN }} -y || true
          vercel env rm NEXTAUTH_URL production --token=${{ secrets.VERCEL_TOKEN }} -y || true

          echo "${{ secrets.AUTH_SECRET }}" | vercel env add AUTH_SECRET production --token=${{ secrets.VERCEL_TOKEN }}
          echo "${{ secrets.AUTH0_ISSUER }}" | vercel env add AUTH0_ISSUER production --token=${{ secrets.VERCEL_TOKEN }}
          echo "${{ secrets.AUTH0_CLIENT_ID }}" | vercel env add AUTH0_CLIENT_ID production --token=${{ secrets.VERCEL_TOKEN }}
          echo "${{ secrets.AUTH0_CLIENT_SECRET }}" | vercel env add AUTH0_CLIENT_SECRET production --token=${{ secrets.VERCEL_TOKEN }}
          echo "${{ secrets.AUTH0_BASE_URL }}" | vercel env add AUTH0_BASE_URL production --token=${{ secrets.VERCEL_TOKEN }}
          echo "${{ secrets.NEXT_PUBLIC_API_URL }}" | vercel env add NEXT_PUBLIC_API_URL production --token=${{ secrets.VERCEL_TOKEN }}
          echo "${{ secrets.NEXTAUTH_URL }}" | vercel env add NEXTAUTH_URL production --token=${{ secrets.VERCEL_TOKEN }}

      # Luego hacemos pull de la información
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      # Después construimos
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      # Finalmente desplegamos
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  deploy-preview:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      # Primero sincronizamos las variables
      - name: Sync Environment Variables
        run: |
          vercel env rm AUTH_SECRET development --token=${{ secrets.VERCEL_TOKEN }} -y || true
          vercel env rm AUTH0_ISSUER development --token=${{ secrets.VERCEL_TOKEN }} -y || true
          vercel env rm AUTH0_CLIENT_ID development --token=${{ secrets.VERCEL_TOKEN }} -y || true
          vercel env rm AUTH0_CLIENT_SECRET development --token=${{ secrets.VERCEL_TOKEN }} -y || true
          vercel env rm AUTH0_BASE_URL_DEVELOPMENT development --token=${{ secrets.VERCEL_TOKEN }} -y || true
          vercel env rm API_URL development --token=${{ secrets.VERCEL_TOKEN }} -y || true
          vercel env rm NEXTAUTH_URL_DEVELOPMENT development --token=${{ secrets.VERCEL_TOKEN }} -y || true

          echo "${{ secrets.AUTH_SECRET }}" | vercel env add AUTH_SECRET development --token=${{ secrets.VERCEL_TOKEN }}
          echo "${{ secrets.AUTH0_ISSUER }}" | vercel env add AUTH0_ISSUER development --token=${{ secrets.VERCEL_TOKEN }}
          echo "${{ secrets.AUTH0_CLIENT_ID }}" | vercel env add AUTH0_CLIENT_ID development --token=${{ secrets.VERCEL_TOKEN }}
          echo "${{ secrets.AUTH0_CLIENT_SECRET }}" | vercel env add AUTH0_CLIENT_SECRET development --token=${{ secrets.VERCEL_TOKEN }}
          echo "${{ secrets.AUTH0_BASE_URL_DEVELOPMENT }}" | vercel env add AUTH0_BASE_URL_DEVELOPMENT development --token=${{ secrets.VERCEL_TOKEN }}
          echo "${{ secrets.NEXT_PUBLIC_API_URL }}" | vercel env add NEXT_PUBLIC_API_URL development --token=${{ secrets.VERCEL_TOKEN }}
          echo "${{ secrets.NEXTAUTH_URL_DEVELOPMENT }}" | vercel env add NEXTAUTH_URL_DEVELOPMENT development --token=${{ secrets.VERCEL_TOKEN }}

      # Luego hacemos pull de la información
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      # Después construimos
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      # Finalmente desplegamos
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
